import { Platform, StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#09110f' },
  backgroundGlow: { ...StyleSheet.absoluteFillObject, opacity: 0.75 },
  scrollContent: { flexGrow: 1 },
  shell: {
    width: '100%',
    maxWidth: 1320,
    alignSelf: 'center',
    paddingHorizontal: 20,
    paddingTop: Platform.OS === 'web' ? 28 : 56,
    paddingBottom: 32,
    gap: 18,
  },
  heroCard: {
    borderRadius: 28,
    borderWidth: 1,
    borderColor: 'rgba(124, 215, 168, 0.16)',
    padding: 24,
    shadowColor: '#020806',
    shadowOffset: { width: 0, height: 20 },
    shadowOpacity: 0.26,
    shadowRadius: 34,
    elevation: 8,
  },
  heroLayout: { flexDirection: 'row', gap: 18, alignItems: 'stretch' },
  heroLayoutStacked: { flexDirection: 'column' },
  heroCopy: { flex: 1.1, gap: 12 },
  heroEyebrow: {
    color: '#7CD7A8',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 1.1,
    textTransform: 'uppercase',
  },
  heroTitle: { color: '#F4FFF8', fontSize: 34, lineHeight: 38, fontWeight: '800' },
  heroSubtitle: { color: '#CFE4DA', fontSize: 16, lineHeight: 24, maxWidth: 640 },
  heroButtons: { flexDirection: 'row', flexWrap: 'wrap', gap: 12, marginTop: 4 },
  primaryAction: { backgroundColor: '#7CD7A8', borderRadius: 14, paddingHorizontal: 16, paddingVertical: 12 },
  primaryActionPressed: { opacity: 0.88 },
  primaryActionText: { color: '#10211d', fontSize: 14, fontWeight: '700' },
  secondaryHeroAction: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(207, 228, 218, 0.18)',
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  secondaryHeroActionText: { color: '#E6F4ED', fontSize: 14, fontWeight: '600' },
  heroFootnote: { color: '#9FC2B1', fontSize: 13, lineHeight: 20 },
  heroSnapshot: { flex: 0.95, gap: 12 },
  statCard: {
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    backgroundColor: 'rgba(7, 16, 13, 0.48)',
    padding: 16,
    gap: 6,
  },
  statLabel: {
    color: '#8FB3A3',
    fontSize: 12,
    textTransform: 'uppercase',
    letterSpacing: 0.9,
    fontWeight: '700',
  },
  statValue: { color: '#F6FFFA', fontSize: 28, fontWeight: '800' },
  statHelper: { color: '#B5D1C4', fontSize: 13, lineHeight: 18 },
  filtersCard: {
    borderRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.07)',
    backgroundColor: 'rgba(9, 20, 17, 0.84)',
    padding: 18,
    gap: 14,
  },
  searchInput: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    backgroundColor: '#11201c',
    color: '#F0FFF6',
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 15,
  },
  filterRow: { flexDirection: 'row', gap: 10, paddingRight: 12 },
  filterChip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    backgroundColor: '#11201c',
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  filterChipActive: { backgroundColor: '#7CD7A8', borderColor: '#7CD7A8' },
  filterChipPressed: { opacity: 0.84 },
  filterChipText: { color: '#D8EEE2', fontSize: 13, fontWeight: '600' },
  filterChipTextActive: { color: '#10211d' },
  mainColumns: { flexDirection: 'row', gap: 18, alignItems: 'flex-start' },
  mainColumnsStacked: { flexDirection: 'column' },
  detailColumn: { flex: 1.25, gap: 14 },
  detailColumnFull: { width: '100%' },
  sidebarColumn: { flex: 0.92, gap: 14 },
  sidebarColumnFull: { width: '100%' },
  sectionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 2 },
  sectionTitle: { color: '#F5FFF9', fontSize: 18, fontWeight: '700' },
  sectionHelper: {
    color: '#8FA99D',
    fontSize: 12,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.7,
  },
  projectGrid: { gap: 12 },
  projectCard: {
    borderRadius: 22,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.07)',
    backgroundColor: 'rgba(11, 23, 20, 0.88)',
    padding: 18,
    gap: 12,
  },
  projectCardSelected: { borderColor: 'rgba(124, 215, 168, 0.42)', backgroundColor: 'rgba(18, 36, 31, 0.96)' },
  projectCardPressed: { opacity: 0.96 },
  projectHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', gap: 12, alignItems: 'flex-start' },
  projectTitleWrap: { flex: 1, gap: 4 },
  projectTitle: { color: '#F2FFF7', fontSize: 18, fontWeight: '700' },
  projectClient: { color: '#89AFA0', fontSize: 13, fontWeight: '600' },
  stageBadge: { borderRadius: 999, borderWidth: 1, paddingHorizontal: 10, paddingVertical: 6 },
  stageBadgeText: { fontSize: 12, fontWeight: '700' },
  projectSummary: { color: '#CBE2D7', fontSize: 14, lineHeight: 21 },
  metaRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  metaLabel: { color: '#90B0A2', fontSize: 12, fontWeight: '600' },
  progressTrack: { height: 8, borderRadius: 999, backgroundColor: 'rgba(255, 255, 255, 0.08)', overflow: 'hidden' },
  progressFill: { height: '100%', borderRadius: 999 },
  progressText: { color: '#A8C6B7', fontSize: 12, fontWeight: '600' },
  tagRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  inlineTag: { borderRadius: 999, backgroundColor: '#11201c', paddingHorizontal: 10, paddingVertical: 6 },
  inlineTagText: { color: '#D8EEE2', fontSize: 11, fontWeight: '700' },
  blockerTag: { backgroundColor: 'rgba(251, 113, 133, 0.12)' },
  blockerTagText: { color: '#FF9FB1' },
  projectActions: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  secondaryAction: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: '#0D1815',
  },
  secondaryActionPressed: { opacity: 0.88 },
  secondaryActionText: { color: '#D6ECE0', fontSize: 13, fontWeight: '700' },
  priorityAction: { backgroundColor: 'rgba(245, 158, 11, 0.12)', borderColor: 'rgba(245, 158, 11, 0.28)' },
  priorityActionText: { color: '#F6BD4C' },
  detailPanel: {
    borderRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.07)',
    backgroundColor: 'rgba(9, 20, 17, 0.88)',
    padding: 18,
    gap: 14,
  },
  detailTitle: { color: '#F5FFF9', fontSize: 24, fontWeight: '800' },
  detailSummary: { color: '#C8E0D4', fontSize: 14, lineHeight: 21 },
  metricRow: { flexDirection: 'row', gap: 10 },
  metricCard: { flex: 1, borderRadius: 18, backgroundColor: '#11201c', padding: 14, gap: 4 },
  metricValue: { color: '#F5FFF9', fontSize: 20, fontWeight: '800' },
  metricLabel: { color: '#8EAB9D', fontSize: 12, fontWeight: '600' },
  panelTitle: { color: '#EBFFF5', fontSize: 14, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.8 },
  panelTitleSpacing: { marginTop: 4 },
  panelGroup: { gap: 10 },
  checklistRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    borderRadius: 16,
    backgroundColor: '#11201c',
    paddingHorizontal: 12,
    paddingVertical: 11,
  },
  checklistRowPressed: { opacity: 0.92 },
  checkbox: {
    width: 28,
    height: 28,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.14)',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#09110f',
  },
  checkboxMark: { color: '#05100D', fontSize: 10, fontWeight: '800' },
  checklistLabel: { flex: 1, color: '#E5F5ED', fontSize: 13, lineHeight: 18 },
  checklistLabelDone: { color: '#91C9AB' },
  notesInput: {
    minHeight: 110,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    backgroundColor: '#11201c',
    color: '#F1FFF8',
    padding: 14,
    fontSize: 14,
    lineHeight: 20,
  },
  timelineRow: { flexDirection: 'row', gap: 12, alignItems: 'flex-start' },
  timelineDot: { width: 10, height: 10, marginTop: 6, borderRadius: 999, backgroundColor: '#7CD7A8' },
  timelineContent: { flex: 1, gap: 3 },
  timelineTitle: { color: '#F0FFF6', fontSize: 14, fontWeight: '700' },
  timelineMeta: { color: '#9AB9AB', fontSize: 12, lineHeight: 18 },
  dimText: { color: '#88A596', fontSize: 13, lineHeight: 20 },
  attentionRow: {
    borderRadius: 16,
    backgroundColor: 'rgba(245, 158, 11, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(245, 158, 11, 0.18)',
    paddingHorizontal: 12,
    paddingVertical: 11,
  },
  attentionText: { color: '#F7CC74', fontSize: 13, lineHeight: 18, fontWeight: '600' },
  emptyCard: {
    borderRadius: 22,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.06)',
    backgroundColor: 'rgba(12, 22, 19, 0.86)',
    padding: 18,
    gap: 8,
  },
  emptyTitle: { color: '#F4FFF8', fontSize: 16, fontWeight: '700' },
  emptyCopy: { color: '#9AB9AA', fontSize: 14, lineHeight: 20 },
});
