import { getPoolProjects } from '/web/shared/project-catalog.mjs';
const descriptions={"gym-scholar":"Training research and practical programming in a live application.",dyslexia:"A reading environment with adjustable typography, spacing, colour, focus, and narration.",audiobook:"A separate audiobook production tab for turning documents into narrated chapters.",flowform:"A reachable movement project that remains honestly labelled In development.","womens-health-os":"A research interface focused on women-specific questions. Its corpus has not yet been verified as exclusively women-focused."};
const colors=['#4b735e','#9b6d45','#786695','#497d89','#9a5d68'],target=document.querySelector('#project-cards');
getPoolProjects('Health').forEach((project,index)=>{const card=document.createElement('article');card.className='project-card';card.style.setProperty('--card-color',colors[index%colors.length]);const binding=project.routeBindings?.find(x=>x.type==='external')||project.routeBindings?.find(x=>x.route);const href=binding?.url||binding?.route;card.innerHTML=`<div class="organelle" aria-hidden="true"></div><span class="status">${project.status}</span><h3>${project.publicName}</h3><p>${descriptions[project.id]||'A catalog-backed Health project.'}</p><div class="card-actions">${href?`<a href="${href}"${href.startsWith('http')?' target="_blank" rel="noopener noreferrer"':''}>Open project</a>`:'<span class="project-link-unavailable" aria-disabled="true" style="opacity:.55">Open project (not yet available)</span>'}<button type="button" data-project-feedback="${project.publicName}">Feedback</button></div>`;target.before(card)});target.remove();
document.addEventListener('click',event=>{const trigger=event.target.closest('[data-project-feedback]');if(!trigger)return;const shared=[...document.querySelectorAll('button')].find(button=>button.textContent==='Feedback'&&!button.dataset.projectFeedback);shared?.click();requestAnimationFrame(()=>{const area=document.querySelector('#sdforest-feedback-message');if(area){area.value=`[${trigger.dataset.projectFeedback}] `;area.focus();area.setSelectionRange(area.value.length,area.value.length)}})});
ScrollCraft.mount(document.body);
// Keyboard entry into a pinned act: the engine centres the focused element, but inside a sticky stage an
// already-centred control can keep the act at a progress where its cue is still dark. Move the act's own
// scroll to a point inside the cue's lit window instead, so focus always lands on something visible.
addEventListener('focusin',event=>{const cue=event.target.closest?.('[data-sc-cue]'),act=cue?.closest('[data-sc-act="pin"]');if(!act)return;requestAnimationFrame(()=>{if(parseFloat(getComputedStyle(cue).opacity)>0.85)return;const n=cue.dataset.scCue.trim().split(/\s+/).map(parseFloat),from=n[0]||0,to=Number.isFinite(n[1])?n[1]:1,p=Math.min(1,from+(to-from)*0.5),top=act.getBoundingClientRect().top+scrollY;scrollTo({top:top+p*Math.max(act.offsetHeight-innerHeight,1),behavior:'instant'})})});
