import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

/**
 * EVERY FIELD THIS PAGE NAMES MUST EXIST IN THE PACKAGE.
 *
 * A previous pass put `measured_from` and `listed_but_unserviceable` on this page. The
 * package emits `vantagePoint` and has no serviceability state at all, so the page was
 * advertising two fields that do not exist -- documentation drifting from the thing it
 * documents, which is exactly the defect the price-set release exists to remove, one
 * layer out. Nobody caught it because nothing could: prose on one side, a schema on the
 * other, and no mechanism between them.
 *
 * package-facts.json is generated by the package's own `generate-docs.ts --facts`,
 * reading the vocabulary out of its zod schemas. This test is the mechanism.
 */
const factsUrl = new URL("./package-facts.json", import.meta.url);
const pageUrl = new URL("./mcp/index.html", import.meta.url);

/**
 * Tokens the page may print that are not package fields: shell words, hostnames, file
 * names, literal enum VALUES, and JSON literals. Kept explicit and short -- a broad
 * pattern here would swallow the very drift this test exists to catch.
 */
const NOT_A_FIELD = new Set([
  "npx", "null", "pricing.md", "api.sailresearch.com",
  // status/state values the page quotes, not field names
  "partial", "approval_incomplete", "collection_disabled",
  // cache metadata the site itself owns
  "ageSeconds", "expiresAt", "fetchedAt",
]);

/**
 * Only identifier-shaped tokens. The page also puts commands, JSON snippets, dates, model
 * slugs and protocol paths in <code>, and none of those is a field claim. The filter is
 * deliberately narrow rather than an ignore-list: a field name IS identifier-shaped, so
 * nothing this test exists to catch can slip through it.
 */
async function pageTokens() {
  const html = await readFile(pageUrl, "utf8");
  const all = [...new Set([...html.matchAll(/<code>([^<]+)<\/code>/g)].map((match) => match[1].trim()))];
  return all.filter((token) => /^[A-Za-z_][A-Za-z0-9_.]*$/.test(token));
}

test("every identifier the MCP page names exists in the package", async () => {
  const facts = JSON.parse(await readFile(factsUrl, "utf8"));
  const c = facts.contract;
  const known = new Set([
    ...facts.tools.map((tool) => tool.name),
    ...c.priceUnits, ...c.conditionKinds, ...c.provenance,
    ...c.speedStates, ...c.tokenBasis,
    ...c.pricePointFields, ...c.speedFields,
    ...c.contractFields, ...c.normalizedFigureFields, ...c.environmentVariables,
    // latency-window condition values, which the page quotes by name
    "ASAP", "Balanced", "Flex",
  ]);

  const unknown = (await pageTokens()).filter((token) => !known.has(token) && !NOT_A_FIELD.has(token));
  assert.deepEqual(unknown, [],
    `The page names identifiers the package does not emit: ${unknown.join(", ")}. ` +
    "Either the package must ship them or the page must stop claiming them.");
});

test("the page does not resurrect the two fields the package never had", async () => {
  // Named explicitly, because these two are what happened rather than what might.
  const html = await readFile(pageUrl, "utf8");
  for (const invented of ["measured_from", "listed_but_unserviceable"]) {
    assert.doesNotMatch(html, new RegExp(invented),
      `${invented} was invented by a previous pass and the package has never emitted it`);
  }
});

test("the page names the package's real tool count and every tool it lists is real", async () => {
  const facts = JSON.parse(await readFile(factsUrl, "utf8"));
  const html = await readFile(pageUrl, "utf8");
  const named = [...new Set([...html.matchAll(/<code>(dashboard_[a-z_]+)<\/code>/g)].map((m) => m[1]))];
  const real = new Set(facts.tools.map((tool) => tool.name));
  assert.deepEqual(named.filter((name) => !real.has(name)), [], "the page lists a tool the server does not register");
  assert.equal(named.length, facts.tools.length,
    `the page names ${named.length} tools; the package registers ${facts.tools.length}`);
});

test("the package facts the page is checked against are the version being described", async () => {
  // A stale manifest would make every assertion above vacuous: the page could agree
  // perfectly with a package nobody ships. Regenerate with `generate-docs.ts --facts`.
  const facts = JSON.parse(await readFile(factsUrl, "utf8"));
  assert.equal(facts.name, "open-dashboard-mcp");
  assert.match(facts.version, /^\d+\.\d+\.\d+$/);
  const html = await readFile(pageUrl, "utf8");
  assert.ok(html.includes(facts.version), `the page must name the version it documents (${facts.version})`);
});
