import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

/**
 * EVERY FIELD THIS PAGE NAMES MUST EXIST IN THE PACKAGE.
 *
 * A previous pass put `measured_from` and `listed_but_unserviceable` on this page. The
 * package emits `vantagePoint` and has no serviceability state at all, so the page was
 * advertising two fields that do not exist -- documentation drifting from the thing it
 * documents, which is exactly the defect the price-set release exists to remove, one
 * layer out. Nobody caught it because nothing could: prose on one side, a schema on the
 * other, and no mechanism between them.
 *
 * package-facts.json is generated by the package's own `generate-docs.ts --facts`,
 * reading the vocabulary out of its zod schemas. This test is the mechanism.
 */
const factsUrl = new URL("./package-facts.json", import.meta.url);
const pageUrl = new URL("./mcp/index.html", import.meta.url);

/**
 * Tokens the page may print that are not package fields: shell words, hostnames, file
 * names, literal enum VALUES, and JSON literals. Kept explicit and short -- a broad
 * pattern here would swallow the very drift this test exists to catch.
 */
const NOT_A_FIELD = new Set([
  "npx", "null", "pricing.md", "api.sailresearch.com",
  // OpenClaw configuration vocabulary, documented by OpenClaw rather than this package
  "mcp.servers", "OPENCLAW_CONFIG_PATH",
  // status/state values the page quotes, not field names
  "partial", "approval_incomplete", "collection_disabled",
  // cache metadata the site itself owns
  "ageSeconds", "expiresAt", "fetchedAt",
]);

/**
 * Only identifier-shaped tokens. The page also puts commands, JSON snippets, dates, model
 * slugs and protocol paths in <code>, and none of those is a field claim. The filter is
 * deliberately narrow rather than an ignore-list: a field name IS identifier-shaped, so
 * nothing this test exists to catch can slip through it.
 */
async function pageTokens() {
  const html = await readFile(pageUrl, "utf8");
  const all = [...new Set([...html.matchAll(/<code>([^<]+)<\/code>/g)].map((match) => match[1].trim()))];
  return all.filter((token) => /^[A-Za-z_][A-Za-z0-9_.]*$/.test(token));
}

test("every identifier the MCP page names exists in the package", async () => {
  const facts = JSON.parse(await readFile(factsUrl, "utf8"));
  const c = facts.contract;
  const known = new Set([
    ...facts.tools.map((tool) => tool.name),
    ...c.priceUnits, ...c.conditionKinds, ...c.provenance,
    ...c.speedStates, ...c.tokenBasis,
    ...c.pricePointFields, ...c.speedFields,
    ...c.contractFields, ...c.normalizedFigureFields, ...c.environmentVariables,
    // latency-window condition values, which the page quotes by name
    "ASAP", "Balanced", "Flex",
  ]);

  const unknown = (await pageTokens()).filter((token) => !known.has(token) && !NOT_A_FIELD.has(token));
  assert.deepEqual(unknown, [],
    `The page names identifiers the package does not emit: ${unknown.join(", ")}. ` +
    "Either the package must ship them or the page must stop claiming them.");
});

test("the page does not resurrect the two fields the package never had", async () => {
  // Named explicitly, because these two are what happened rather than what might.
  const html = await readFile(pageUrl, "utf8");
  for (const invented of ["measured_from", "listed_but_unserviceable"]) {
    assert.doesNotMatch(html, new RegExp(invented),
      `${invented} was invented by a previous pass and the package has never emitted it`);
  }
});

test("the page names the package's real tool count and every tool it lists is real", async () => {
  const facts = JSON.parse(await readFile(factsUrl, "utf8"));
  const html = await readFile(pageUrl, "utf8");
  const named = [...new Set([...html.matchAll(/<code>(dashboard_[a-z_]+)<\/code>/g)].map((m) => m[1]))];
  const real = new Set(facts.tools.map((tool) => tool.name));
  assert.deepEqual(named.filter((name) => !real.has(name)), [], "the page lists a tool the server does not register");
  assert.equal(named.length, facts.tools.length,
    `the page names ${named.length} tools; the package registers ${facts.tools.length}`);
});

test("the package facts the page is checked against are the version being described", async () => {
  // A stale manifest would make every assertion above vacuous: the page could agree
  // perfectly with a package nobody ships. Regenerate with `generate-docs.ts --facts`.
  const facts = JSON.parse(await readFile(factsUrl, "utf8"));
  assert.equal(facts.name, "open-dashboard-mcp");
  assert.match(facts.version, /^\d+\.\d+\.\d+$/);
  const html = await readFile(pageUrl, "utf8");
  assert.ok(html.includes(facts.version), `the page must name the version it documents (${facts.version})`);
});

test("the page's 1.0 content only uses vocabulary the package actually defines", async () => {
  // mcp-1.0-content.json is the substrate the page renders and the next task reads. It is
  // hand-authored, so it is exactly the kind of file that drifts from the package while
  // still looking authoritative -- which is the defect this whole release is about. Every
  // term it uses is checked against package-facts.json, which is generated from the zod
  // schemas.
  const facts = JSON.parse(await readFile(factsUrl, "utf8"));
  const content = JSON.parse(await readFile(new URL("./mcp-1.0-content.json", import.meta.url), "utf8"));
  const c = facts.contract;

  assert.equal(content.packageVersion, facts.version, "the content must name the package version it describes");

  for (const entry of content.conditionKinds) {
    assert.ok(c.conditionKinds.includes(entry.kind), `condition kind ${entry.kind} is not in the package`);
  }
  assert.deepEqual(
    content.conditionKinds.map((k) => k.kind).sort(),
    [...c.conditionKinds].sort(),
    "the page must cover every condition kind the package defines, and invent none",
  );

  assert.deepEqual([...content.provenance.values].sort(), [...c.provenance].sort());
  assert.deepEqual([...content.speed.tokenBasis.values].sort(), [...c.tokenBasis].sort());
  for (const field of content.speed.requiredFields) {
    assert.ok(c.speedFields.includes(field), `speed field ${field} is not emitted by the package`);
  }

  // A kind with no producer must say so rather than carrying a fabricated instance.
  for (const entry of content.conditionKinds) {
    if (entry.emitted === false) {
      assert.equal(entry.instance, null, `${entry.kind} claims an instance while declaring itself unemitted`);
      assert.ok(entry.note, `${entry.kind} is unemitted and must explain that, not just omit it`);
    } else {
      assert.ok(entry.instance && entry.instance.provider, `${entry.kind} claims to be emitted but names no real instance`);
    }
  }

  // EVERY VOCABULARY-BEARING VALUE, not a selected few. The first version of this test
  // checked condition kinds, provenance, token basis and speed fields and stopped there,
  // so priceSet.example.unit, measuredParity.metric, withheldClaims[].state and
  // threeStates[].state could all drift to terms the package does not define while it
  // stayed green. Reviewer-caught as a coverage gap; a guard with holes in it is how the
  // page drifted in the first place.
  assert.ok(c.priceUnits.includes(content.priceSet.example.unit),
    `the price-set example uses unit ${content.priceSet.example.unit}, which the package does not define`);

  const stateVocabulary = new Set([...c.speedStates, "not_published"]);
  for (const s of content.threeStates) {
    assert.ok(stateVocabulary.has(s.state), `three-states names ${s.state}, which the package does not define`);
  }
  for (const w of content.speed.withheldClaims) {
    assert.ok(c.speedStates.includes(w.state), `withheld claim for ${w.provider} reports ${w.state}, not a speed state`);
  }
  assert.ok(
    content.speed.measuredParity.metric === "TTFT" || c.speedFields.includes(content.speed.measuredParity.metric),
    `measuredParity.metric ${content.speed.measuredParity.metric} is neither TTFT nor a speed field`,
  );
  assert.ok(c.tokenBasis.includes(content.speed.measuredParity.tokenBasis),
    "the parity measurement names a token basis the package does not define");

  // The three states must stay distinguishable by their rendered glyph, which is the
  // matrixCellModel defect generalised: two states sharing a glyph are one state.
  const glyphs = content.threeStates.map((s) => s.glyph);
  assert.equal(new Set(glyphs).size, glyphs.length, "two states share a glyph, so a reader cannot tell them apart");
  assert.ok(!glyphs.some((g) => /^\d+$/.test(g)), "no state may render as a bare number");
});

test("package-facts.json is the SHIPPED package's vocabulary, not a copy that drifted", async () => {
  // THE GUARD WAS COUPLED TO THE WRONG ARTIFACT and the review said so. Every other test
  // in this file checks the page against package-facts.json -- a file committed into THIS
  // repo. Nothing tied it back to the package, so a stale or hand-edited copy would keep
  // all of them green while the published package documented different fields entirely.
  // A check aimed at the wrong layer, which is the defect this whole page is about.
  //
  // open-dashboard-mcp is now a devDependency and ships build/contract-vocabulary.json,
  // generated from its own zod schemas. That file is the authority; package-facts.json
  // must agree with it exactly.
  //
  // This deliberately HARD-FAILS when the package is not installed. Skipping would restore
  // precisely the vacuum it exists to close.
  let shipped;
  try {
    shipped = (await import("open-dashboard-mcp/contract-vocabulary.json", { with: { type: "json" } })).default;
  } catch (error) {
    assert.fail(
      "open-dashboard-mcp is not installed, so the page's facts cannot be checked against the real package. " +
      "Run `npm install`. Never soften this to a skip: an unverifiable guard is worse than none. " + String(error),
    );
  }

  const facts = JSON.parse(await readFile(factsUrl, "utf8"));
  assert.equal(facts.name, shipped.name);
  assert.equal(facts.version, shipped.version,
    `package-facts.json describes ${facts.version} but the installed package is ${shipped.version}; regenerate it`);
  assert.deepEqual(facts.contract, shipped.contract,
    "package-facts.json disagrees with the vocabulary the package actually ships");
  assert.deepEqual(
    facts.tools.map((t) => t.name).sort(),
    [...shipped.tools].sort(),
    "the tool list in package-facts.json is not the tool list the package registers",
  );
});
